version: "3.5"

services:
  db:
    image: postgres
    ports:
      - "5001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
volumes:
  pgdata:
      
      
    